vich_uploader:
    db_driver: orm
    mappings:
        photo_upload:
            uri_prefix: /upload/img/photos
            upload_destination: '%kernel.project_dir%/public/upload/img/photos'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
